# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_mat_mult2 <- function(A, B) {
    .Call('_cleverly_fast_mat_mult2', PACKAGE = 'cleverly', A, B)
}

fast_mat_mult <- function(A, B) {
    .Call('_cleverly_fast_mat_mult', PACKAGE = 'cleverly', A, B)
}

